### ISSUE TITLE
crash when length is zero

### ISSUE THREAD

**Issue by neoneye** [TheDarkCode/SwiftyLevenshtein#2]
This code causes a crash 

    _ = "monalisa1234567".getLevenshtein("")

Console output

    fatal error: Can't form Range with upperBound < lowerBound

The crash happens in the for loop, where targetLength is zero

    for y in 1...targetLength {
        
        distance[0, y] = y
        
    }

**Comment by 1ec5** [comment]
The current code still crashes in the same manner as in the original report:

https://github.com/TheDarkCode/SwiftyLevenshtein/blob/5bacd3941943939871b4d452e4b70999c0a99828/SwiftyLevenshtein.swift#L149-L159
